<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:macro name="connect4_board">
        
        <!-- Camera stuff: see https://classic.gazebosim.org/tutorials?tut=ros_gzplugins -->


        <joint name="board_joint" type="fixed">
            <axis xyz="1 0 0" />
            <!-- <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/> -->
            <origin xyz="0.25 -0.25 0" rpy="0 0 0"/>
            <parent link="world"/>
            <child link="board_link"/>
        </joint>

        <!-- Camera -->
        <link name="board_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.57 0 0" />
                <geometry>
                    <mesh filename="package://ece383-final-project/meshes/visual/board.stl" scale="0.001 0.001 0.001">
                    </mesh>
                </geometry>
                <material name="">
                    <color rgba="1 1 0 1" />
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="1.57 0 0" />
                <geometry>
                    <mesh filename="package://ece383-final-project/meshes/visual/board.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>

            <inertial>
                <mass value="1e-1" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-1" ixy="0" ixz="0" iyy="1e-1" iyz="0" izz="1e-1" />
            </inertial>
        </link>

        <gazebo reference="board_link">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>
</robot>